- type: entity
  id: BaseStationEmergencyAccessMedbayState
  abstract: true
  components:
  - type: EmergencyAccessMedbayState

- type: entity
  id: BaseStationCodeBlueSecretState
  abstract: true
  components:
  - type: CodeBlueSecretState
